components:
  schemas:
    Pet:
      example:
        id: 1
        name: Rex
        tag: dog
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        tag:
          type: string
      required:
      - id
      - name
      - names
      type: object
    Pets:
      example:
      - id: 1
        name: Fido
        names:
        - Fido
        - Buddy
      - id: 2
        name: Whiskers
        names:
        - Whiskers
        - Kitty
      items:
        $ref: '#/components/schemas/Pet'
      maxItems: 100
      type: array
info:
  license:
    name: MIT
  title: Swagger Petstore
  version: 1.0.0
openapi: 3.0.0
paths:
  /pets:
    get:
      operationId: listPets
      parameters:
      - description: How many items to return at one time (max 100)
        example: 10
        in: query
        name: limit
        required: false
        schema:
          properties:
            code:
              format: int32
              type: integer
            message:
              type: string
          required:
          - code
          - message
          type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
        default:
          content:
            application/json:
              schema:
                properties:
                  code:
                    format: int32
                    type: integer
                  message:
                    type: string
                required:
                - code
                - message
                type: object
          description: unexpected error
      summary: List all pets
      tags:
      - pets
    post:
      operationId: createPets
      responses:
        "201":
          description: Null response
        default:
          content:
            application/json:
              schema:
                properties:
                  code:
                    format: int32
                    type: integer
                  message:
                    type: string
                required:
                - code
                - message
                type: object
          description: unexpected error
      summary: Create a pet
      tags:
      - pets
  /pets/{petId}:
    get:
      operationId: showPetById
      parameters:
      - description: ID of pet to return
        in: path
        name: petId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: Expected response to a valid request
        default:
          content:
            application/json:
              schema:
                properties:
                  code:
                    format: int32
                    type: integer
                  message:
                    type: string
                required:
                - code
                - message
                type: object
          description: unexpected error
      summary: Info for a specific pet
      tags:
      - pets
servers:
- url: http://petstore.swagger.io/v1
tags:
- name: pets
